#!/usr/bin/env bash
# This script displays username, user id, and home directory from /etc/passwd
while IFS=: read -r username _ uid _ _ homedir _
do
    echo "$username:$uid:$homedir"
done < /etc/passwd
