#!/usr/bin/env bash
# This script displays the content of /etc/passwd as a story
while IFS=: read -r username password uid gid userinfo homedir shell
do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
